name: hallboking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^2.0.7
  date_picker_timeline: ^1.2.3
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http: ^0.13.4
  uuid: ^3.0.6
  shared_preferences: ^2.0.15




flutter:
  uses-material-design: true
  assets:
    - assest/


